# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog, limba):
        self.language = limba
        Dialog.setObjectName("Dialog")
        Dialog.resize(441, 300)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 10, 381, 121))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("sigla-standard-RGB.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(140, 140, 191, 51))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(100, 200, 250, 51))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        if self.language == 'EN':
            Dialog.setWindowTitle(_translate("Dialog", "About"))
            self.label_2.setText(_translate("Dialog", "Student: Tanasă Alin-Petru"))
            self.label_3.setText(_translate("Dialog", "Teacher: prof. dr. ing. Potorac Alin Dan"))
        elif self.language == 'RO':
            Dialog.setWindowTitle(_translate("Dialog", "Despre"))
            self.label_2.setText(_translate("Dialog", "Student: Tanasă Alin-Petru"))
            self.label_3.setText(_translate("Dialog", "Îndrumător: prof. dr. ing. Potorac Alin Dan"))
