# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddPI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from head import Ui_MainWindow as head

class Ui_Dialog(object):
    def setupUi(self, Dialog, limba):
        self.language = limba
        Dialog.setObjectName("Dialog")
        Dialog.resize(304, 239)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(-120, 190, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.buttonBox.accepted.connect(self.accept)
        self.label = QtWidgets.QLabel(Dialog)
        if self.language == 'EN':
            self.label.setGeometry(QtCore.QRect(60, 80, 61, 17))
        elif self.language == 'RO':
            self.label.setGeometry(QtCore.QRect(10, 80, 81, 17))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(100, 30, 113, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(100, 80, 113, 25))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtWidgets.QLabel(Dialog)
        if self.language == 'EN':
            self.label_2.setGeometry(QtCore.QRect(10, 30, 88, 17))
        elif self.language == 'RO':
            self.label_2.setGeometry(QtCore.QRect(10, 30, 90, 27))
        self.label_2.setObjectName("label_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(100, 130, 113, 25))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(38, 130, 71, 27))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        if self.language == 'EN':
            Dialog.setWindowTitle(_translate("Dialog", "Connect to Raspberry PI"))
            self.label.setText(_translate("Dialog", "PI's IP:"))
            self.label_2.setText(_translate("Dialog", "PI's Username:"))
            self.label_3.setText(_translate("Dialog", "File Name:"))
        elif self.language == 'RO':
            Dialog.setWindowTitle(_translate("Dialog", "Conectare la Raspberry PI"))
            self.label.setText(_translate("Dialog", "IP-ul lui PI:"))
            self.label_2.setText(_translate("Dialog", "Numele de \n utilizator:"))
            self.label_3.setText(_translate("Dialog", "Numele\nfișierului:"))

    def accept(self):
        window = QtWidgets.QMainWindow()
        graph = head()
        graph.setupUi(window, self.lineEdit.text(), self.lineEdit_2.text(), self.lineEdit_3.text(), self.language)
        window.show()
        window.exec_()
