# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Graph.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pyqtgraph as pg

class Ui_Dialog(object):
    def setupUi(self, Dialog, timp, pachete, limba):
        Dialog.setObjectName("Graph")
        Dialog.resize(631, 550)
        self.language = limba
        self.centralwidget = QtWidgets.QWidget(Dialog)
        self.centralwidget.setObjectName("centralwidget")
        self.graphWidget = pg.PlotWidget(self.centralwidget)
        self.graphWidget.setGeometry(QtCore.QRect(0, 0, 631, 550))
        self.graphWidget.setObjectName("graph")
        hour = timp
        temperature = pachete
        if self.language == 'EN':
            self.graphWidget.setLabel("left", "Packets")
            self.graphWidget.setLabel("bottom", "Time (miliseconds)")
        elif self.language == 'RO':
            self.graphWidget.setLabel("left", "Pachete de date")
            self.graphWidget.setLabel("bottom", "Timp (milisecunde)")
        self.graphWidget.plot(hour, temperature)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        if self.language == 'EN':
            Dialog.setWindowTitle(_translate("Graph", "Graph"))
        elif self.language == 'RO':
            Dialog.setWindowTitle(_translate("Graph", "Grafic"))


