# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'save.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    stream = []
    def setupUi(self, Dialog, stram, limba):
        self.language = limba
        Dialog.setObjectName("Dialog")
        Dialog.resize(338, 201)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(-90, 120, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.stream = stram
        self.buttonBox.accepted.connect(self.accept)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(140, 30, 67, 17))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(90, 60, 161, 25))
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        if self.language == 'EN':
            Dialog.setWindowTitle(_translate("Dialog", "Save"))
            self.label.setText(_translate("Dialog", "File Name"))
        elif self.language == 'RO':
            Dialog.setWindowTitle(_translate("Dialog", "Save"))
            self.label.setText(_translate("Dialog", "File Name"))

    def accept(self):
        nume = '{}.txt'.format(self.lineEdit.text())
        with open(nume, 'w') as r:
            for info in self.stream:
                eth, ipv4 = info
                r.write('Source:{} Destination:{} Protocol:{} destination MAC: {} source MAC:' 
                        '{}\n'.format(ipv4[4], ipv4[5], ipv4[3], eth[0], eth[1]))

